@host=127.0.0.1
@port=8888
@userId=15
@userName="x"
@userPassword="123456"
@userCurrentPassword="654321"

@roleName="超级管理员"
@roleId=5

@menuURL="test"
@menuName="测试"
@menuId=1

### 创建用户
POST http://{{host}}:{{port}}/users
Content-Type: application/json

{
  "name": {{userName}},
  "password": {{userPassword}},
  "description": "测试用户"
}

### 修改用户信息
PUT http://{{host}}:{{port}}/users/{{userId}}
Content-Type: application/json

{
  "name": {{userName}},
  "password": {{userPassword}},
  "description": "管理员"
}

### 删除用户
DELETE http://{{host}}:{{port}}/users/{{userId}}

### 获取用户
GET http://{{host}}:{{port}}/users/{{userId}}

### 获取用户列表
GET http://{{host}}:{{port}}/users

### 登录
POST http://{{host}}:{{port}}/users/login
Content-Type: application/json

{
  "name": {{userName}},
  "password": {{userPassword}}
}

### 修改密码
PUT http://{{host}}:{{port}}/users/change/password/{{userId}}
Content-Type: application/json

{
  "origin_password": {{userPassword}},
  "current_password": {{userCurrentPassword}}
}

### 重置密码
PUT http://{{host}}:{{port}}/users/reset/password/{{userId}}

### 创建角色
POST http://{{host}}:{{port}}/roles
Content-Type: application/json

{
  "name": {{roleName}}
}

### 更新角色
PUT http://{{host}}:{{port}}/roles/{{roleId}}
Content-Type: application/json

### 删除角色
DELETE http://{{host}}:{{port}}/roles/{{roleId}}
Content-Type: application/json

### 获取角色
GET http://{{host}}:{{port}}/roles/{{roleId}}
Content-Type: application/json

### 获取角色列表
GET http://{{host}}:{{port}}/roles
Content-Type: application/json

### 创建菜单
POST http://{{host}}:{{port}}/menus
Content-Type: application/json

{
  "url": {{menuURL}},
  "name": {{menuName}}
}

### 更新菜单
PUT http://{{host}}:{{port}}/menus/{{menuId}}
Content-Type: application/json

### 删除菜单
DELETE http://{{host}}:{{port}}/menus/{{menuId}}
Content-Type: application/json

### 获取菜单
GET http://{{host}}:{{port}}/menus/{{menuId}}
Content-Type: application/json

### 获取菜单列表
GET http://{{host}}:{{port}}/menus
Content-Type: application/json